name: Build and Publish to NuGet.org

on:
  push:
    branches: [ master ]
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    env:
      CONFIGURATION: Release
      DOTNET_NOLOGO: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration $CONFIGURATION --no-restore

      - name: Pack NuGet (with symbols and source)
        run: |
          VERSION=${GITHUB_REF##*/}
          VERSION=${VERSION#v}
          dotnet pack **/*.csproj \
            --configuration $CONFIGURATION \
            --output ./nupkgs \
            --include-symbols --include-source \
            /p:PackageVersion=$VERSION

      - name: Push to NuGet.org
        run: |
          dotnet nuget push ./nupkgs/*.nupkg \
            --source https://api.nuget.org/v3/index.json \
            --api-key ${{ secrets.NUGET_API_KEY }}