name: Build and Publish to NuGet.org

on:
  push:
    branches:
      - master
      - 
permissions:
  contents: write
  packages: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    env:
      CONFIGURATION: Release
      DOTNET_NOLOGO: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore ./WiSave.Shared.OpenTelemetry/WiSave.Shared.OpenTelemetry.csproj

      - name: Build project
        run: dotnet build ./WiSave.Shared.OpenTelemetry/WiSave.Shared.OpenTelemetry.csproj --configuration $CONFIGURATION --no-restore

      - name: Set version number
        run: echo "VERSION=1.0.${{ github.run_number }}" >> $GITHUB_ENV

      - name: Pack NuGet package
        run: |
          dotnet pack ./WiSave.Shared.OpenTelemetry/WiSave.Shared.OpenTelemetry.csproj \
            --configuration $CONFIGURATION \
            --output ./nupkgs \
            --include-symbols --include-source \
            /p:PackageVersion=$VERSION

      - name: Push to NuGet.org
        run: |
          dotnet nuget push ./nupkgs/*.nupkg \
            --source "https://nuget.pkg.github.com/JacobChwastek/index.json" \
            --api-key "${{ secrets.NUGET_PACKAGE_TOKEN }}" \
            --skip-duplicate